[package]
name = "pager"
version = "0.1.0"
authors = [
    "ticki <ticki@users.noreply.github.com>",
    "Jeremy Soller <jackpot51@gmail.com>"
]

[dependencies]
termion = { git = "https://github.com/redox-os/termion.git" }
